### ISSUE TITLE
School Data from API Has A Whole Bunch of nulls

### ISSUE THREAD

**Issue by sherl0cks** [unicef/colombia_mapping_project#8]
I pulled the data being served for Columbia from my browser just to check it out. There are more `null` entries in the JSON than entries with meaningful data.

**Comment by mikefab** [comment]
Thank you for mentioning this. First, two notes:
- This issue is more relevant to github.com/unicef/magicbox-open-api.
- This particular repo has moved to https://github.com/unicef/maps

Explanation:
This API response was designed to accommodate a partner's requirements while they were rapidly prototyping. Now that they've completed their POC, we've since acquired their project and are refactoring.

The initial requirement was to return all school data for a requested country.
- Fields related to connectivity determined the color of each data point.
- Most other fields were used to display school details in a dialog box on point click.

We are now revising that end point to only return fields for ID, geo coordinates, and connection.
On point click will send a request to a new end point that will return data for a specific school.

**Comment by sherl0cks** [comment]
Sounds good. Closing
